name: Spinjitzu
version: '1.0-SNAPSHOT'
main: me.thundercaster.spinjitzu.Spinjitzu
api-version: 1.16
authors: [ Thundercaster ]
description: Spinjitzu plugin from ninja go
commands:
  spinjitzu:
    -description: 'p cool'